spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twilio
    username: asus
    password: asus
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8080

twilio:
  account-cid: test
  auth-token: test
  phone-number: test
